name: mobile staging app updates
on:
  push:
    branches:
      - master
    paths:
      - "packages/app-mobile/**"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    env:
      EXPO_USE_DEV_SERVER: true
      TMPDIR: /tmp # Used for metro caching
      NODE_OPTIONS: "--max_old_space_size=4096"
      APP_ENV: staging

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸŒ Setup SSH for trek-api-web-ts submodule
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SUBMODULE_TREK_API }}

      - run: git submodule update --init && rm -f packages/trek-api-web-ts/yarn.lock

      - name: ğŸŒ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Cache Metro
        uses: actions/cache@v3
        id: cache-metro
        with:
          path: |
            ${{ env.TMPDIR }}/metro-cache
            ${{ env.TMPDIR }}/haste-map*
          key: npm-${{ env.NODE_VERSION }}-${{ runner.os }}

      - name: ğŸš€ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ§¶ Install dependencies
        run: yarn install --immutable

      - name: ğŸ—ï¸ Build dependencies
        run: yarn build:mobile

      - name: ğŸš€ Publish iOS Update
        working-directory: ./packages/app-mobile
        run: APP_ENV="staging" eas update --auto --branch ios-staging -p ios

      - name: ğŸš€ Publish Android Update
        working-directory: ./packages/app-mobile
        run: APP_ENV="staging" eas update --auto --branch android-staging -p android
