name: Deploy backend-api
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "mv docker/backpack-api/Dockerfile ."

      - name: add secrets
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          cd backend/native/backpack-api
          touch .env
          printf 'NODE_ENV=production\n' >> .env
          printf 'AUTH_JWT=%s\n' '${{secrets.AUTH_JWT}}' >> .env
          printf 'AUTH_JWT_PRIVATE_KEY=%s\n' '${{secrets.AUTH_JWT_PRIVATE_KEY}}' >> .env
          printf 'AUTH_JWT_PUBLIC_KEY=%s\n' '${{secrets.AUTH_JWT_PUBLIC_KEY}}' >> .env
          printf 'AWS_S3_KEY_ID=%s\n' '${{secrets.AWS_S3_KEY_ID}}' >> .env
          printf 'AWS_S3_KEY_SECRET=%s\n' '${{secrets.AWS_S3_KEY_SECRET}}' >> .env
          printf 'COINGECKO_API_KEY=%s\n' '${{secrets.COINGECKO_API_KEY}}' >> .env
          printf 'HASURA_URL=%s\n' '${{secrets.HASURA_URL}}' >> .env
          printf 'CHAT_HASURA_URL=%s\n' '${{secrets.CHAT_HASURA_URL}}' >> .env
          printf 'REDIS_URL=%s\n' '${{secrets.REDIS_URL}}' >> .env
          printf 'CHAT_JWT=%s\n' '${{secrets.CHAT_JWT}}' >> .env
          printf 'HELIUS_API_KEY=%s\n' '${{secrets.HELIUS_API_KEY}}' >> .env
          printf 'VAPID_PRIVATE_KEY=%s\n' '${{secrets.VAPID_PRIVATE_KEY}}' >> .env
          printf 'VAPID_PUBLIC_KEY=%s\n' '${{secrets.VAPID_PUBLIC_KEY}}' >> .env
          printf 'SENTRY_DSN=%s\n' '${{secrets.SENTRY_DSN}}' >> .env
          printf 'TWITTER_CONSUMER_KEY=%s\n' '${{secrets.TWITTER_CONSUMER_KEY}}' >> .env
          printf 'TWITTER_CONSUMER_SECRET=%s\n' '${{secrets.TWITTER_CONSUMER_SECRET}}' >> .env
          printf 'OVERRIDE_RPC_URL=%s\n' '${{secrets.OVERRIDE_RPC_URL}}' >> .env
          printf 'TENSOR_API_KEY=%s\n' '${{secrets.TENSOR_API_KEY}}' >> .env
          cd ../../..

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --tag backpackapp/backpack-api:${{ github.sha }}

      - name: Docker Push
        run: docker push backpackapp/backpack-api:${{ github.sha }}

      - name: Create zip
        run: "mkdir deploy && cp ./docker/backpack-api/docker-compose.yml ./deploy && cp ./docker/Dockerrun.aws.json ./deploy && sed 's/{{tag}}/${{ github.sha }}/g' ./deploy/docker-compose.yml > ./deploy/temp.yml && mv ./deploy/temp.yml ./deploy/docker-compose.yml && cd deploy && zip deploy.zip * && cd .. && mv ./deploy/deploy.zip ."

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: backend-api
          environment_name: backend-api-dockerhub
          version_label: ${{ github.sha }}
          region: us-west-1
          deployment_package: deploy.zip
